### ISSUE TITLE
Python 3 multiple errors

### ISSUE THREAD

**Issue by Name277** [ShaneLee/Youtube-Email-Bulk-Downloader#1]
I am getting the above error when I try to run getvideo.py, I am using python 3.8.2 and I tried using other versions as well but had the same result.

**Comment by ShaneLee** [comment]
@Name277 Hi, 

I see you have closed this - did you get it sorted? 

Thanks

Shane

**Comment by Name277** [comment]
@ShaneLee yep I did, thanks. I just have a problem with python 3. It is the yt_file.py around line 28 about the msg variable. 'msg = email.message_from_string(response_part[1])' which gave me this error: 
'initial_value must be str or None, not bytes'

so I placed '.decode('utf8')' so it looked like this: 
msg = email.message_from_string(response_part[1].decode('utf8'))
and the error was gone

But after that it gave me another error:

https://www.youtube.com/watch?v=XT0u8egOMvg
Traceback (most recent call last):
  File "getvideo.py", line 8, in <module>
    pytube.YouTube(link).streams.first().download('.')
  File "C:\Users\iphon\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 91, in __init__
    self.prefetch()
  File "C:\Users\iphon\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 183, in prefetch
    self.js_url = extract.js_url(self.watch_html)
  File "C:\Users\iphon\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\extract.py", line 143, in js_url
    base_js = get_ytplayer_config(html)["assets"]["js"]
  File "C:\Users\iphon\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\extract.py", line 202, in get_ytplayer_config
    raise RegexMatchError(caller="get_ytplayer_config", pattern="config_patterns")
pytube.exceptions.RegexMatchError: get_ytplayer_config: could not find match for config_patterns

**Comment by Name277** [comment]
This was a strange error but it was because of an invalid youtube url link, the video was removed from youtube and that error diplayed, so it works really great. Other than that I only recieved a very few errors about the modules and some problems with google authentication. I'd say this issue should be closed, thanks.
